version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sys-affichage
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - database:/var/lib/postgresql/data

  server:
    container_name: affichage_server
    restart: unless-stopped
    image: affichage_server:0.1.0
    environment:
      - NODE_ENV=production
      - PORT=8080
      - ALLOWED_ORIGINS=http://localhost:5173
      - DATABASE_URL=postgresql://user:password@host:port/sys-affichage?schema=public
      - JWT_ACCESS_SECRET=jwt-token
      - ACCESS_DURATION=8h
      - FB_PAGE_ID=page-id
      - FB_PAGE_ACCESS_TOKEN=token
      - FB_APP_ID=app-id
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      - postgres

  client:
    container_name: affichage_client
    restart: unless-stopped
    image: affichage_client:0.1.0
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - shared-network
    depends_on:
      - server

networks:
  shared-network:

volumes:
  database:
